template = "https://github.com/giellalt/template-lang-und"
rev_id = 302
template_sha = "b3740681672fe3b348eb75d3170f7a2da900a0b1"

[replacements]
__GLOTTOLOG_ID__ = "apur1254"
__REPO__ = "lang-apu"
__UND2C__ = "apu"
__UNDEFINED__ = "Apurinã"
__UND__ = "apu"
