template = "https://github.com/giellalt/template-lang-und"
rev_id = 295
template_sha = "9e160f410d669a53f8b740a218fd6462f17d3234"

[replacements]
__GLOTTOLOG_ID__ = "apur1254"
__REPO__ = "lang-apu"
__UND2C__ = "apu"
__UNDEFINED__ = "Apurinã"
__UND__ = "apu"
