[package]
name = "apu"
human_name = "Apurinã"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.apu]
filename = "apu-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-apu"
platform = "windows"
uuid = "98C480D9-52E0-474D-B18C-7A1EB7C7EE4E"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.apu"
package = "speller-apu"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-apu-mso"
platform = "windows"
uuid = "0C947DF1-82FE-4C91-A2D0-ED546F2B7084"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-apu"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
